print("      *\n     * *\n    *   *\n   *     *\n  *       *\n ****   ****\n    *   *\n    *   *\n    *   *\n    *****")

print("    *   ")
print("   * *  ")
print("  *   * ")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *")
print("  *   *")
print("  *****")